export const ROUTER_MAP: Record<string, string> = {
  HOME: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  OPERATIONS: "/dashboard/operations",
  OPERATIONS_CREATE: "/dashboard/operations/create",
  OPERATIONS_EDIT: "/dashboard/operations/edit",
  WALLETS: "/dashboard/wallets",
  WALLETS_CREATE: "/dashboard/wallets/create",
  GUIDES: "/dashboard/guides",
  GUIDES_CREATE: "/dashboard/guides/create",
  GUIDES_EDIT: "/dashboard/guides/edit",
  APPLICATIONS: "/dashboard/applications",
  APPLICATIONS_EDIT: "/dashboard/applications/edit",
  USERS: "/dashboard/users",
  HELP: "/dashboard/help",
  FEEDBACK: "/dashboard/feedback",
  ANALYTICS: "/dashboard/analytics",
  REPORTS: "/dashboard/reports",
  CREATE_USER: "/dashboard/create",
  SETTINGS: "/dashboard/settings",
  ERROR: "/error",
};

export const ROUTER_TITLES: Record<string, string> = {
  [ROUTER_MAP.HOME]: "MonteMove",
  [ROUTER_MAP.LOGIN]: "Вход",
  [ROUTER_MAP.DASHBOARD]: "Панель управления",
  [ROUTER_MAP.OPERATIONS]: "Операции",
  [ROUTER_MAP.OPERATIONS_CREATE]: "Создание",
  [ROUTER_MAP.OPERATIONS_EDIT]: "Редактирование",
  [ROUTER_MAP.WALLETS]: "Кошельки",
  [ROUTER_MAP.WALLETS_CREATE]: "Создать кошелек",
  [ROUTER_MAP.GUIDES]: "Справочники",
  [ROUTER_MAP.GUIDES_CREATE]: "Создание",
  [ROUTER_MAP.GUIDES_EDIT]: "Редактирование",
  [ROUTER_MAP.APPLICATIONS]: "Заявки",
  [ROUTER_MAP.APPLICATIONS_EDIT]: "Редактирование заявки",
  [ROUTER_MAP.USERS]: "Пользователи",
  [ROUTER_MAP.HELP]: "Помощь",
  [ROUTER_MAP.FEEDBACK]: "Обратная связь",
  [ROUTER_MAP.ANALYTICS]: "Аналитика",
  [ROUTER_MAP.REPORTS]: "Отчеты",
  [ROUTER_MAP.SETTINGS]: "Настройки",
};
